---
# tasks file for setup-kubernetes
- name: Set up kernel modules
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      br_netfilter

- name: Set up sysctl parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl parameters without reboot
  command: sysctl --system

- name: Install Kubernetes dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - curl

- name: Download public signing key for Kubernetes package repositories
  shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Create /etc/apt/keyrings directory if it doesn't exist (for older releases)
  file:
    path: /etc/apt/keyrings
    state: directory
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int < 12 or ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 22

- name: Replace Kubernetes repository definition
  shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Kubernetes components
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold Kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl