---
# tasks file for role

  - name: Set up container runtime prereqs - create modules-load.d file
    copy:
      dest: /etc/modules-load.d/containerd.conf
      content: |
        overlay
        br_netfilter

  - name: Load kernel modules
    shell: |
      modprobe overlay
      modprobe br_netfilter

  - name: Set up sysctl parameters
    copy:
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      content: |
        net.bridge.bridge-nf-call-iptables  = 1
        net.ipv4.ip_forward                 = 1
        net.bridge.bridge-nf-call-ip6tables = 1

  - name: Apply sysctl parameters without reboot
    shell: sysctl --system
    changed_when: false

  - name: Install containerd on Ubuntu
    apt:
      name: containerd
      update_cache: yes

  - name: Download and extract containerd binary
    shell: |
      wget https://github.com/containerd/containerd/releases/download/v1.7.15/containerd-1.7.15-linux-amd64.tar.gz 
      tar xvf containerd-1.6.15-linux-amd64.tar.gz
      mv bin/* /usr/bin/
    notify: Restart containerd

  - name: Create containerd directory
    file:
      path: /etc/containerd
      state: directory

  - name: Configure containerd
    copy:
      dest: /etc/containerd/config.toml
      content: |
        version = 2
        [plugins]
          [plugins."io.containerd.grpc.v1.cri"]
            [plugins."io.containerd.grpc.v1.cri".containerd]
              discard_unpacked_layers = true
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  runtime_type = "io.containerd.runc.v2"
                  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                    SystemdCgroup = true
    notify: Restart containerd
