on:
  push:
    branches:
      - master
  
jobs:
  deploy-and-config:
    name: Deploy Infrastructure with Terraform and config with Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.3.9
            # for TF Cloud
            # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform init
        run: terraform init
        working-directory: infra
      - name: Terraform Plan
        run: terraform plan
        working-directory: infra
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: python3 -m pip install --user ansible
      - name: Check Version of Ansible
        run: ansible --version
      - name: Configure SSH key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/ansible_key
          chmod 600 ~/.ssh/ansible_key
      - name: Run Ansible playbook
        run: ansible-playbook playbooks/setup-k8s-cluster.yaml
        env:
          ANSIBLE_CONFIG: ./ansible.cfg
        working-directory: config