on:
  pull_request:
    branches:
      - master
  
jobs:
  terraform-plan:
    name: Run Terraform Plan
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.3.9
      - name: Terraform init
        run: terraform init
        working-directory: infra
      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan
        working-directory: infra
      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Terraform Plan Output:
            ```
            ${{ steps.terraform-plan.outputs.stdout }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  